// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sztehkqatsjutvmudccz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6dGVoa3FhdHNqdXR2bXVkY2N6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MzY2MTQsImV4cCI6MjA2NTUxMjYxNH0.MBeANpRliLVKdYeUHYsZ-GQ7D2bttUBXwIyCYxGI9Aw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);